// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlghlbluoyecskpzpjmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ2hsYmx1b3llY3NrcHpwam1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjgzMjksImV4cCI6MjA2MDkwNDMyOX0.9zyS8wG4ijkqCM-00A6Q1t4g2s3wbKtmD60CCHYKK5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);